#!/usr/bin/env bash
TOOL_DIR="$( cd "$( dirname "$0"  )" && pwd  )"
mongod --dbpath /mongodb/mongodb &
for i in 1 2 3 4 5 6 7 8 9 10;
do
    curl --connect-timeout 1 localhost:27017 > /dev/null 2>/dev/null
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 1
done

python $TOOL_DIR/mt_console.py $@
# killall mongod
